### ISSUE TITLE
missing entry point libobjc.A.dylib on arm64 dotnet-sdk

### ISSUE THREAD

**Issue by PhantomCloak** [ImGuiNET/ImGui.NET#352]
I encounter `System.EntryPointNotFoundException` exception for `libobjc.A.dylib`  when trying to launch sample program with arm64 dotnet-sdk, in case of x64 dotnet-sdk sample program runs successfully

```
  Unhandled exception. System.EntryPointNotFoundException: Unable to find an entry point named 'objc_msgSend_stret' in shared library '/usr/lib/libobjc.A.dylib'.
   at Veldrid.MetalBindings.ObjectiveCRuntime.objc_msgSend_stret(Void* retPtr, IntPtr receiver, Selector selector)
   at Veldrid.MetalBindings.ObjectiveCRuntime.objc_msgSend_stret[T](IntPtr receiver, Selector selector)
   at Veldrid.MetalBindings.NSView.get_frame()
   at Veldrid.MTL.MTLSwapchain..ctor(MTLGraphicsDevice gd, SwapchainDescription& description)
   at Veldrid.MTL.MTLGraphicsDevice..ctor(GraphicsDeviceOptions options, Nullable`1 swapchainDesc)
   at Veldrid.GraphicsDevice.CreateMetal(GraphicsDeviceOptions options, SwapchainDescription swapchainDescription)
   at Veldrid.StartupUtilities.VeldridStartup.CreateMetalGraphicsDevice(GraphicsDeviceOptions options, Sdl2Window window, Boolean colorSrgb)
   at Veldrid.StartupUtilities.VeldridStartup.CreateMetalGraphicsDevice(GraphicsDeviceOptions options, Sdl2Window window)
   at Veldrid.StartupUtilities.VeldridStartup.CreateGraphicsDevice(Sdl2Window window, GraphicsDeviceOptions options, GraphicsBackend preferredBackend)
   at Veldrid.StartupUtilities.VeldridStartup.CreateWindowAndGraphicsDevice(WindowCreateInfo windowCI, GraphicsDeviceOptions deviceOptions, GraphicsBackend preferredBackend, Sdl2Window& window, GraphicsDevice& gd)
   at Veldrid.StartupUtilities.VeldridStartup.CreateWindowAndGraphicsDevice(WindowCreateInfo windowCI, GraphicsDeviceOptions deviceOptions, Sdl2Window& window, GraphicsDevice& gd)

```

ls output

```
~ ❯ ls -al /usr/lib | grep libobjc
-rwxr-xr-x    1 root  wheel   297536 Jul  6 09:27 libobjc-trampolines.dylib
lrwxr-xr-x    1 root  wheel       15 Jul  6 09:27 libobjc.dylib -> libobjc.A.dylib
```
Setup
---------------
OS: MacOS Ventura 13.0
SDK Version: 6.0.401
SDK Architecture: arm64
ImGui.NET Version: at master/lastest(#0938c98)

**Comment by jhgorse** [comment]
Can confirm the same attempting to use Veldrid sdl2 on m2 laptop running macOS.

```
jhgs-MacBook-Air:ImGui.NET.SampleProgram jhg$ dotnet run
Unhandled exception. System.EntryPointNotFoundException: Unable to find an entry point named 'objc_msgSend_stret' in shared library '/usr/lib/libobjc.A.dylib'.
   at Veldrid.MetalBindings.ObjectiveCRuntime.objc_msgSend_stret(Void* retPtr, IntPtr receiver, Selector selector)
   at Veldrid.MetalBindings.ObjectiveCRuntime.objc_msgSend_stret[T](IntPtr receiver, Selector selector)
   at Veldrid.MetalBindings.NSView.get_frame()
   at Veldrid.MTL.MTLSwapchain..ctor(MTLGraphicsDevice gd, SwapchainDescription& description)
   at Veldrid.MTL.MTLGraphicsDevice..ctor(GraphicsDeviceOptions options, Nullable`1 swapchainDesc)
   at Veldrid.GraphicsDevice.CreateMetal(GraphicsDeviceOptions options, SwapchainDescription swapchainDescription)
   at Veldrid.StartupUtilities.VeldridStartup.CreateMetalGraphicsDevice(GraphicsDeviceOptions options, Sdl2Window window, Boolean colorSrgb)
   at Veldrid.StartupUtilities.VeldridStartup.CreateMetalGraphicsDevice(GraphicsDeviceOptions options, Sdl2Window window)
   at Veldrid.StartupUtilities.VeldridStartup.CreateGraphicsDevice(Sdl2Window window, GraphicsDeviceOptions options, GraphicsBackend preferredBackend)
   at Veldrid.StartupUtilities.VeldridStartup.CreateWindowAndGraphicsDevice(WindowCreateInfo windowCI, GraphicsDeviceOptions deviceOptions, GraphicsBackend preferredBackend, Sdl2Window& window, GraphicsDevice& gd)
   at Veldrid.StartupUtilities.VeldridStartup.CreateWindowAndGraphicsDevice(WindowCreateInfo windowCI, GraphicsDeviceOptions deviceOptions, Sdl2Window& window, GraphicsDevice& gd)
   at ImGuiNET.Program.Main(String[] args) in /opt/work/ImGui.NET/src/ImGui.NET.SampleProgram/Program.cs:line 41
```

Was able to resolve the issue with refreshing the Veldrid package within the sample project directory:
```
dotnet add package Veldrid
```
<img width="1284" alt="image" src="https://github.com/ImGuiNET/ImGui.NET/assets/1783474/22e71f7f-8d6e-43ca-b18c-a29cb2676616">

**Comment by PhantomCloak** [comment]
Thanks for the feedback since I'm not working on this right now, I assume this is the valid solution so I'm closing this issue.
